version: '3.4'

services:
  grand.web:

    ports:
      - 80
      - 443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=madison
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./conf.d/https/:/https/

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
  db:
    image: mongo
