<Project Sdk="Microsoft.NET.Sdk.Razor">
    <Import Project="..\..\Build\Grand.Common.props" />
    <Import Project="..\..\Build\Grand.Plugin.props" />
    <PropertyGroup>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
	</PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <OutputPath>..\..\Web\Grand.Web\Plugins\Payments.StripeCheckout\</OutputPath>
        <OutDir>$(OutputPath)</OutDir>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <OutputPath>..\..\Web\Grand.Web\Plugins\Payments.StripeCheckout\</OutputPath>
        <OutDir>$(OutputPath)</OutDir>
    </PropertyGroup>

    <ItemGroup>
		<PackageReference Include="Stripe.net" />
    </ItemGroup>

    

    <ItemGroup>
        <None Update="logo.jpg">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\" />
    </ItemGroup>
    
</Project>