<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Business\Grand.Business.Core\Grand.Business.Core.csproj" />
    <ProjectReference Include="..\..\Core\Grand.Infrastructure\Grand.Infrastructure.csproj" />
    <ProjectReference Include="..\Grand.Web.Common\Grand.Web.Common.csproj" />
  </ItemGroup>

</Project>
